### ISSUE TITLE
Could not find a package configuration file provided by "CUDAToolkit" with

### ISSUE THREAD

**Issue by JACKLiuDay** [koide3/gtsam_points#36]
![image](https://github.com/user-attachments/assets/2dd87fd8-46cb-4a24-a9a0-9c1e66a474d6)
I have installed CUDA 12.2, but I encounter an error during the compilation.

**Comment by JACKLiuDay** [comment]
![image](https://github.com/user-attachments/assets/05e8c684-8174-4ee5-8e72-b7df274e4bee)

**Comment by koide3** [comment]
Mabe the version of cmake is too old? Please try installing a newer version of cmake: https://apt.kitware.com/

**Comment by JACKLiuDay** [comment]
> Mabe the version of cmake is too old? Please try installing a newer version of cmake: https://apt.kitware.com/

Thank you very much for your reply. I will try updating the CMake version. Currently, I am using the CPU version of gtsam_points and Glim, and after that, we will try running the GPU version of gtsam_points and Glim.
